pub struct Keybinding {
    pub keys: &'static str,
    pub description: &'static str,
}

pub fn bindings_for_view(view: &str) -> Vec<Keybinding> {
    match view {
        "Home" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "help.navigate" },
            Keybinding { keys: "Enter", description: "help.open_item" },
            Keybinding { keys: "/", description: "help.search" },
            Keybinding { keys: "f", description: "help.follow" },
            Keybinding { keys: "z", description: "help.toggle_favorite" },
            Keybinding { keys: "e", description: "help.series_info" },
            Keybinding { keys: "F/Z", description: "help.favorites" },
            Keybinding { keys: "u", description: "help.accounts" },
            Keybinding { keys: "s", description: "help.settings" },
            Keybinding { keys: "Ctrl+F", description: "help.refresh" },
            Keybinding { keys: "?", description: "help.help" },
            Keybinding { keys: "Esc/Backspace", description: "help.back" },
            Keybinding { keys: "q", description: "help.quit" },
        ],
        "Libraries" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "help.navigate" },
            Keybinding { keys: "Enter", description: "help.open_library" },
            Keybinding { keys: "s", description: "help.settings" },
            Keybinding { keys: "?", description: "help.help" },
            Keybinding { keys: "q", description: "help.quit" },
        ],
        "Items" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "help.navigate" },
            Keybinding { keys: "Enter", description: "help.open_item" },
            Keybinding { keys: "/", description: "help.search" },
            Keybinding { keys: "f", description: "help.follow" },
            Keybinding { keys: "z", description: "help.toggle_favorite" },
            Keybinding { keys: "e", description: "help.series_info" },
            Keybinding { keys: "F/Z", description: "help.favorites" },
            Keybinding { keys: "s", description: "help.settings" },
            Keybinding { keys: "Ctrl+F", description: "help.refresh" },
            Keybinding { keys: "?", description: "help.help" },
            Keybinding { keys: "Esc/Backspace", description: "help.back" },
            Keybinding { keys: "q", description: "help.quit" },
        ],
        "Episodes" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "help.navigate" },
            Keybinding { keys: "Enter", description: "help.play_episode" },
            Keybinding { keys: "e", description: "help.series_info" },
            Keybinding { keys: "?", description: "help.help" },
            Keybinding { keys: "Esc", description: "help.back" },
            Keybinding { keys: "q", description: "help.quit" },
        ],
        "SeriesInfo" => vec![
            Keybinding { keys: "←/→ h/l", description: "help.switch_section" },
            Keybinding { keys: "↑/↓ k/j", description: "help.navigate" },
            Keybinding { keys: "Enter", description: "help.open_item" },
            Keybinding { keys: "f", description: "help.follow" },
            Keybinding { keys: "e", description: "help.episodes" },
            Keybinding { keys: "?", description: "help.help" },
            Keybinding { keys: "Esc", description: "help.back" },
            Keybinding { keys: "q", description: "help.quit" },
        ],
        "Playing" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "help.select_scroll" },
            Keybinding { keys: "PageUp/Dn", description: "help.scroll_output" },
            Keybinding { keys: "Enter", description: "help.confirm" },
            Keybinding { keys: "?", description: "help.help" },
            Keybinding { keys: "Esc", description: "help.back" },
            Keybinding { keys: "q", description: "help.quit" },
        ],
        "LibraryBrowser" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "help.navigate" },
            Keybinding { keys: "Enter", description: "help.open_item" },
            Keybinding { keys: "/", description: "help.search" },
            Keybinding { keys: "e", description: "help.series_info" },
            Keybinding { keys: "z", description: "help.toggle_favorite" },
            Keybinding { keys: "Z", description: "help.favorites" },
            Keybinding { keys: "c", description: "help.clear_filters" },
            Keybinding { keys: "Ctrl+S", description: "help.sort" },
            Keybinding { keys: "Ctrl+F", description: "help.filter" },
            Keybinding { keys: "?", description: "help.help" },
            Keybinding { keys: "Esc", description: "help.back" },
            Keybinding { keys: "q", description: "help.quit" },
        ],
        "Favorites" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "help.navigate" },
            Keybinding { keys: "Enter", description: "help.open_item" },
            Keybinding { keys: "/", description: "help.search" },
            Keybinding { keys: "f", description: "help.follow" },
            Keybinding { keys: "z", description: "help.unfavorite" },
            Keybinding { keys: "m", description: "help.mark_watched" },
            Keybinding { keys: "e", description: "help.series_info" },
            Keybinding { keys: "Ctrl+F", description: "help.refresh" },
            Keybinding { keys: "?", description: "help.help" },
            Keybinding { keys: "Esc/Backspace", description: "help.back" },
            Keybinding { keys: "q", description: "help.quit" },
        ],
        "Settings" => vec![
            Keybinding { keys: "Tab", description: "help.next_section" },
            Keybinding { keys: "↑/↓ k/j", description: "help.navigate" },
            Keybinding { keys: "←/→ h/l", description: "help.toggle_switch" },
            Keybinding { keys: "Space", description: "help.toggle_item" },
            Keybinding { keys: "Shift+↑↓ K/J", description: "help.move_item" },
            Keybinding { keys: "Enter", description: "help.save" },
            Keybinding { keys: "Esc", description: "help.cancel" },
            Keybinding { keys: "q", description: "help.quit" },
        ],
        _ => vec![],
    }
}

pub fn view_label_key(view: &str) -> &'static str {
    match view {
        "Home" => "help.view.home",
        "Libraries" => "help.view.libraries",
        "Items" => "help.view.items",
        "Episodes" => "help.view.episodes",
        "SeriesInfo" => "help.view.series_info",
        "Playing" => "help.view.playing",
        "LibraryBrowser" => "help.view.library_browser",
        "Favorites" => "help.view.favorites",
        "Settings" => "help.view.settings",
        _ => "help.view.home",
    }
}
