pub struct Keybinding {
    pub keys: &'static str,
    pub description: &'static str,
}

pub fn bindings_for_view(view: &str) -> Vec<Keybinding> {
    match view {
        "Home" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "Navigate" },
            Keybinding { keys: "Enter", description: "Open item" },
            Keybinding { keys: "/", description: "Search" },
            Keybinding { keys: "f", description: "Follow series" },
            Keybinding { keys: "z", description: "Toggle favorite" },
            Keybinding { keys: "e", description: "Series info" },
            Keybinding { keys: "F/Z", description: "Favorites" },
            Keybinding { keys: "u", description: "Accounts" },
            Keybinding { keys: "s", description: "Settings" },
            Keybinding { keys: "Ctrl+F", description: "Refresh" },
            Keybinding { keys: "?", description: "Help" },
            Keybinding { keys: "Esc/Backspace", description: "Back" },
            Keybinding { keys: "q", description: "Quit" },
        ],
        "Libraries" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "Navigate" },
            Keybinding { keys: "Enter", description: "Open library" },
            Keybinding { keys: "s", description: "Settings" },
            Keybinding { keys: "?", description: "Help" },
            Keybinding { keys: "q", description: "Quit" },
        ],
        "Items" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "Navigate" },
            Keybinding { keys: "Enter", description: "Open item" },
            Keybinding { keys: "/", description: "Search" },
            Keybinding { keys: "f", description: "Follow series" },
            Keybinding { keys: "z", description: "Toggle favorite" },
            Keybinding { keys: "e", description: "Series info" },
            Keybinding { keys: "F/Z", description: "Favorites" },
            Keybinding { keys: "s", description: "Settings" },
            Keybinding { keys: "Ctrl+F", description: "Refresh" },
            Keybinding { keys: "?", description: "Help" },
            Keybinding { keys: "Esc/Backspace", description: "Back" },
            Keybinding { keys: "q", description: "Quit" },
        ],
        "Episodes" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "Navigate" },
            Keybinding { keys: "Enter", description: "Play episode" },
            Keybinding { keys: "e", description: "Series info" },
            Keybinding { keys: "?", description: "Help" },
            Keybinding { keys: "Esc", description: "Back" },
            Keybinding { keys: "q", description: "Quit" },
        ],
        "SeriesInfo" => vec![
            Keybinding { keys: "←/→ h/l", description: "Switch section" },
            Keybinding { keys: "↑/↓ k/j", description: "Navigate" },
            Keybinding { keys: "Enter", description: "Open item" },
            Keybinding { keys: "f", description: "Follow series" },
            Keybinding { keys: "e", description: "Episodes" },
            Keybinding { keys: "?", description: "Help" },
            Keybinding { keys: "Esc", description: "Back" },
            Keybinding { keys: "q", description: "Quit" },
        ],
        "Playing" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "Select / scroll" },
            Keybinding { keys: "PageUp/Dn", description: "Scroll mpv output" },
            Keybinding { keys: "Enter", description: "Confirm / play" },
            Keybinding { keys: "?", description: "Help" },
            Keybinding { keys: "Esc", description: "Back" },
            Keybinding { keys: "q", description: "Quit" },
        ],
        "LibraryBrowser" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "Navigate" },
            Keybinding { keys: "Enter", description: "Open item" },
            Keybinding { keys: "/", description: "Search" },
            Keybinding { keys: "e", description: "Series info" },
            Keybinding { keys: "z", description: "Toggle favorite" },
            Keybinding { keys: "Z", description: "Favorites" },
            Keybinding { keys: "c", description: "Clear filters" },
            Keybinding { keys: "Ctrl+S", description: "Sort" },
            Keybinding { keys: "Ctrl+F", description: "Filter" },
            Keybinding { keys: "?", description: "Help" },
            Keybinding { keys: "Esc", description: "Back" },
            Keybinding { keys: "q", description: "Quit" },
        ],
        "Favorites" => vec![
            Keybinding { keys: "↑/↓ k/j", description: "Navigate" },
            Keybinding { keys: "Enter", description: "Open item" },
            Keybinding { keys: "/", description: "Search" },
            Keybinding { keys: "f", description: "Follow series" },
            Keybinding { keys: "z", description: "Unfavorite" },
            Keybinding { keys: "m", description: "Mark watched" },
            Keybinding { keys: "e", description: "Series info" },
            Keybinding { keys: "Ctrl+F", description: "Refresh" },
            Keybinding { keys: "?", description: "Help" },
            Keybinding { keys: "Esc/Backspace", description: "Back" },
            Keybinding { keys: "q", description: "Quit" },
        ],
        "Settings" => vec![
            Keybinding { keys: "Tab", description: "Next section" },
            Keybinding { keys: "↑/↓ k/j", description: "Navigate" },
            Keybinding { keys: "←/→ h/l", description: "Toggle / switch" },
            Keybinding { keys: "Space", description: "Toggle item" },
            Keybinding { keys: "Shift+↑↓ K/J", description: "Move item" },
            Keybinding { keys: "Enter", description: "Save" },
            Keybinding { keys: "Esc", description: "Cancel" },
            Keybinding { keys: "q", description: "Quit" },
        ],
        _ => vec![],
    }
}

pub fn view_label(view: &str) -> &'static str {
    match view {
        "Home" => "Home",
        "Libraries" => "Libraries",
        "Items" => "Items",
        "Episodes" => "Episodes",
        "SeriesInfo" => "Series Info",
        "Playing" => "Playing",
        "LibraryBrowser" => "Library Browser",
        "Favorites" => "Favorites",
        "Settings" => "Settings",
        _ => "Help",
    }
}
